# pdf_report.py
# Generates a professional PDF report for each investigation

from fpdf import FPDF
from datetime import datetime

class AegisReport(FPDF):
    def header(self):
        self.set_fill_color(20, 30, 48)
        self.rect(0, 0, 210, 25, 'F')
        self.set_text_color(255, 255, 255)
        self.set_font("DejaVu", "B", 14)
        self.set_xy(10, 7)
        self.cell(0, 10, "AEGIS PROBE - Security Investigation Report", align="L")
        self.set_text_color(0, 0, 0)
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font("DejaVu", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Generated by Aegis Probe | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Page {self.page_no()}", align="C")


def generate_pdf_report(case_id, parsed_alert, analysis, probe_results, final_verdict):
    pdf = AegisReport()

    # Add Unicode fonts
    pdf.add_font("DejaVu", "",  "DejaVuSansCondensed.ttf")
    pdf.add_font("DejaVu", "B", "DejaVuSansCondensed-Bold.ttf")
    pdf.add_font("DejaVu", "I", "DejaVuSansCondensed-Oblique.ttf")

    pdf.add_page()
    pdf.set_margins(15, 30, 15)
    pdf.set_auto_page_break(auto=True, margin=20)

    # Clean emojis for PDF
    clean_verdict = final_verdict.replace("🔴", "[DANGEROUS]").replace("🟡", "[MONITOR]")

    # ── Case Header ──
    pdf.set_font("DejaVu", "B", 13)
    pdf.set_fill_color(20, 30, 48)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(180, 10, f"  Case #{case_id} - Investigation Report",
             fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    # Timestamp
    pdf.set_font("DejaVu", "", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(180, 6, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)

    # ── Verdict Banner ──
    if "DANGEROUS" in final_verdict:
        pdf.set_fill_color(220, 50, 50)
    else:
        pdf.set_fill_color(200, 120, 0)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("DejaVu", "B", 11)
    pdf.cell(180, 9, f"  FINAL VERDICT: {clean_verdict}",
             fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    # ── Section 1: Alert Details ──
    section_header(pdf, "1. ALERT DETAILS")
    pdf.set_font("DejaVu", "", 10)
    pdf.set_fill_color(245, 245, 245)
    pdf.multi_cell(180, 7, parsed_alert["raw_alert"], fill=True)
    pdf.ln(2)

    pdf.set_font("DejaVu", "B", 10)
    pdf.multi_cell(180, 7, f"Keywords: {', '.join(parsed_alert['keywords']) if parsed_alert['keywords'] else 'None'}")

    pdf.set_font("DejaVu", "B", 10)
    pdf.multi_cell(180, 7, f"IPs Detected: {', '.join(parsed_alert['ips']) if parsed_alert['ips'] else 'None'}")

    # ── Section 2: AI Analysis ──
    section_header(pdf, "2. MISTRAL AI ANALYSIS")
    if analysis and analysis not in ["None", "Mistral timed out. Please try again."]:
        for line in analysis.split("\n"):
            line = line.strip()
            if not line:
                pdf.ln(2)
                continue
            if any(line.startswith(f"{i}.") for i in range(1, 7)):
                pdf.set_font("DejaVu", "B", 10)
            else:
                pdf.set_font("DejaVu", "", 10)
            pdf.multi_cell(180, 6, line)
    else:
        pdf.set_font("DejaVu", "", 10)
        pdf.set_text_color(150, 150, 150)
        pdf.multi_cell(180, 7, "AI analysis not available for this case.")
        pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    # ── Section 3: Probe Results ──
    section_header(pdf, "3. THREAT INTELLIGENCE PROBE RESULTS")

    for probe in probe_results:
        pdf.set_fill_color(220, 220, 220)
        pdf.set_font("DejaVu", "B", 10)
        pdf.cell(180, 8, f"  IP Address: {probe['ip']}",
                 fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        if probe.get("abuseipdb"):
            ab = probe["abuseipdb"]
            pdf.set_font("DejaVu", "B", 10)
            pdf.cell(180, 6, "AbuseIPDB Results:",
                     new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("DejaVu", "", 10)
            pdf.cell(60, 6, f"  Abuse Score: {ab['abuse_confidence_score']}%")
            pdf.cell(60, 6, f"Total Reports: {ab['total_reports']}")
            pdf.cell(60, 6, f"Country: {ab.get('country') or 'Unknown'}",
                     new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)

        if probe.get("virustotal"):
            vt = probe["virustotal"]
            pdf.set_font("DejaVu", "B", 10)
            pdf.cell(180, 6, "VirusTotal Results:",
                     new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("DejaVu", "", 10)
            pdf.cell(60, 6, f"  Malicious: {vt['malicious_count']}")
            pdf.cell(60, 6, f"Suspicious: {vt['suspicious_count']}")
            pdf.cell(60, 6, f"Harmless: {vt['harmless_count']}",
                     new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)

        verdict = probe.get("verdict", "UNKNOWN")
        clean_pv = verdict.replace("🔴", "[DANGEROUS]").replace("🟡", "[MONITOR]")
        if "DANGEROUS" in verdict:
            pdf.set_fill_color(220, 50, 50)
        else:
            pdf.set_fill_color(200, 120, 0)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("DejaVu", "B", 10)
        pdf.cell(180, 7, f"  Verdict: {clean_pv}",
                 fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(4)

    # ── Section 4: Recommendations ──
    section_header(pdf, "4. RECOMMENDED ACTIONS")
    pdf.set_font("DejaVu", "", 10)
    recommendations = [
        "1. Isolate any affected hosts from the network immediately.",
        "2. Block all flagged IP addresses at the firewall level.",
        "3. Collect and preserve all relevant logs for forensic analysis.",
        "4. Notify the incident response team and relevant stakeholders.",
        "5. Perform a full malware scan on affected systems.",
        "6. Review and update firewall and IDS/IPS rules.",
        "7. Document all findings in the evidence ledger for audit purposes."
    ]
    for rec in recommendations:
        pdf.multi_cell(180, 7, rec)
    pdf.ln(5)

    filename = f"D:\\aegis_probe\\Case_{case_id}_Report.pdf"
    pdf.output(filename)
    print(f"[+] PDF Report saved: {filename}")
    return filename


def section_header(pdf, title):
    pdf.set_fill_color(41, 128, 185)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("DejaVu", "B", 10)
    pdf.cell(180, 8, f"  {title}",
             fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)


# Test it
if __name__ == "__main__":
    test_parsed = {
        "raw_alert": "Malware detected on host 10.0.0.5, suspicious process beacon.exe connecting to IP 185.220.101.45",
        "keywords": ["malware", "suspicious"],
        "ips": ["10.0.0.5", "185.220.101.45"]
    }
    test_analysis = """1. ATTACK TYPE: Remote Access Trojan (RAT) / C2 Communication
2. SEVERITY: High
3. HYPOTHESIS 1: Malware on host established C2 connection to attacker server
4. HYPOTHESIS 2: Insider threat misusing beacon.exe
5. EVIDENCE TO COLLECT: Network logs, process registry, IDS/IPS logs
6. RECOMMENDED ACTION: Isolate host, block IP, notify IR team"""

    test_probes = [{
        "ip": "185.220.101.45",
        "abuseipdb": {"abuse_confidence_score": 100, "total_reports": 96, "country": "DE"},
        "virustotal": {"malicious_count": 16, "suspicious_count": 3, "harmless_count": 59},
        "verdict": "🔴 DANGEROUS"
    }]

    generate_pdf_report(8, test_parsed, test_analysis, test_probes, "🔴 DANGEROUS")
    print("✅ Test PDF generated! Check D:\\aegis_probe\\")